<a href="https://colab.research.google.com/github/StephenSzulc/4AI3-Project/blob/visualization/4AI3_Project_ClassicalApproach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import
from sklearn import linear_model
import numpy as np
import cv2
import pandas as pd
from tensorflow import keras
from keras.datasets import cifar10
from keras.datasets.cifar10 import load_data
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

#set train and test
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

#print shapes
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

#print first value in arrays
print(x_train[0])
print(y_train[0])

170498071/170498071 [==============================] - 8s 0us/step
(50000, 32, 32, 3)
(10000, 32, 32, 3)
(50000, 1)
(10000, 1)
[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]
[6]


In [2]:
# reshape x to 2D to use with linear regression
x_train = x_train.reshape(50000, 32*32*3)
x_test= x_test.reshape(10000, 32*32*3)

#print to see new shape
print(x_train.shape)
print(x_train)

(50000, 3072)
[[ 59  62  63 ... 123  92  72]
 [154 177 187 ... 143 133 144]
 [255 255 255 ...  80  86  84]
 ...
 [ 35 178 235 ...  12  31  50]
 [189 211 240 ... 195 190 171]
 [229 229 239 ... 163 163 161]]


In [3]:
# fit model with training variables
M_Linear = linear_model.LinearRegression()
M_Linear.fit(x_train,y_train)

# see score based on fitting
M_Linear.score(x_test,y_test)

0.02634806717868421